name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          path: rayjslib

      - name: Checkout emscripten-core/emsdk
        uses: actions/checkout@v4.1.1
        with:
          repository: emscripten-core/emsdk
          path: emsdk
      
      - name: Build
        run: |
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          cd ../rayjslib
          npm install
          npm run build

      - name: Delete tag and release
        uses: dev-drprasad/delete-tag-and-release@v1.0.1
        with:
          delete_release: true
          tag_name: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release to GitHub
        uses: ncipollo/release-action@v1
        with:
          name: Latest Release
          tag: latest
          commit: main
          body: ${{ github.event.head_commit.message }}
          artifacts: "rayjslib/build/rayjslib*"
          prerelease: true
