name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: "Setup Emscripten toolchain"
        uses: mymindstorm/setup-emsdk@v14
      
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Build
        run: |
          npm install
          npm run build

      - name: Delete tag and release
        uses: dev-drprasad/delete-tag-and-release@v1.0.1
        with:
          delete_release: true
          tag_name: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release to GitHub
        uses: ncipollo/release-action@v1
        with:
          name: Latest Release
          tag: latest
          commit: main
          body: ${{ github.event.head_commit.message }}
          artifacts: "build/rayjslib*"
          prerelease: true
